pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                script{
                    sh './gradlew clean build'
                }
            }
        }
        stage('Validate azure'){
            environment {
                AZURE_RESOURCE_GROUP = 'rsg-my-learning'
                AZURE_APP_SERVICE_NAME = 'jwt-user-authentication-service'
            }
            steps{
                script{
                    withCredentials([azureServicePrincipal('8386d4ac-0575-4a56-904b-b579c7df6e4e')]) {
                        sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
                        sh 'echo $(pwd)'
                        sh 'az account set --subscription $AZURE_SUBSCRIPTION_ID'
                        sh "az webapp deployment source config-zip --src ./build/libs/user-authentication-service.jar -g $AZURE_RESOURCE_GROUP --n $AZURE_APP_SERVICE_NAME"
                    }
                }
            }
            // }
        }

    }
}