pipeline {
    agent any

    environment{
        AZURE_AKV_CLIENT_ID = '297e0ae5-0036-40b8-9663-4cadfa085017'
        AZURE_AKV_CLIENT_SECRET = 'nsb8Q~aOG3ibjOFoiRB6yAY1Q69k6I8DDx1fybx5'
        AZURE_AKV_TENANT_ID = '285d47ad-d84e-4e26-8bb0-c8cd97c4c2f7'
    }

    stages{
        stage('Build'){
            steps{
             sh "./gradlew clean build --x test"
            }
        }

        stage('Test'){
            steps{
                sh "./gradlew clean test"
            }
        }

        stage{
            steps{

            }
        }
    }
}