pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                script{
                    sh 'gradle clean build'
                }
            }
        }
        stage('Validate azure'){
            environment {
                AZURE_RESOURCE_GROUP = 'rsg-my-learning'
                AZURE_APP_SERVICE_NAME = 'jwt-user-authentication-service'
            }
            steps{
                script{
                    withCredentials([azureServicePrincipal('3224f117-f1c8-4c16-af61-6fc5e39fd1fb')]) {
                        sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
                        sh 'echo $(pwd)'
                        sh 'az account set --subscription $AZURE_SUBSCRIPTION_ID'
                        sh "az webapp deployment source config-zip --src ./build/libs/user-authentication-service.jar -g $AZURE_RESOURCE_GROUP --n $AZURE_APP_SERVICE_NAME"
                    }
                }
            }
            // }
        }

    }
}