spring:
  datasource:
    url: jdbc:postgresql://jwt-user-auth.postgres.database.azure.com:5432/postgres
    username: userauth
    password: ${jwt-user-auth-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    azure:
      keyvault:
        enabled: true
        secret:
          property-sources[0]:
            endpoint: https://user-auth-vault.vault.azure.net/
            credential:
              client-id: f9b0724a-9fbf-4186-86a9-14fbfefc90fe
              client-secret: b4d9f7ca-a6e4-48a8-92c6-851f4fb5b7b1
            profile:
              tenant-id: b4d9f7ca-a6e4-48a8-92c6-851f4fb5b7b1